# Generated by Django 5.1 on 2024-09-20 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('text', models.TextField(default='Some text')),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 20, 13, 24, 15, 589570))),
            ],
        ),
    ]
